# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wap-apac-oauth-oidc-flask-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: index.docker.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8CCB04675CE947E5B35B75F181217705 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_A42B4BBB11684F21843211ACDCAE5062 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8CCB04675CE947E5B35B75F181217705 }}/oauth-oidc-flask-app:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CB1A632ACCD74DE1ADECB7ACBD954E44 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BE574706F08D45DEBB7F740E13A5312F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_314221EA1DDF4C0DAF3B00B100BE2623 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'wap-apac-oauth-oidc-flask-app'
          slot-name: 'Production'
          images: 'index.docker.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8CCB04675CE947E5B35B75F181217705 }}/oauth-oidc-flask-app:${{ github.sha }}'
          